### PR TITLE
Bump to 1.1.1o

### PR DESCRIPTION
**Pull request by amousset**

### CODE REVIEW

**Comment by amousset** [comment]
I checked it with current version to be sure and it fails too, so I'm disabling it.

**Comment by amousset** [comment]
I'll have a look at what is included

**Comment by amousset** [comment]
It happens because of the new `wycheproof` submodule (which seems to be initialized automatically when updating the openssl submodule), when cloning `openssl-src-rs` from scratch and non-recursively initializing submodules, I get a size similar to previous releases.

**Comment by alexcrichton** [comment]
Ah ok that was [fixed on `main`](https://github.com/alexcrichton/openssl-src-rs/pull/110) awhile back. Would you be interested in backporting that?

**Comment by amousset** [comment]
Sure!

**Pull request merged**
