### PR TITLE
Bump to 3.2.0

### PR DESCRIPTION
**Pull request by amousset**
Still working on reducing the size of the crate, a lof of big stuff was added.

### CODE REVIEW

**Comment by alexcrichton** [comment]
If it's too difficult to trim out the extra bits I can also email crates.io folks to try to get the size limit for this crate increased to 20M for example.

**Comment by alexcrichton** [comment]
Want to try rebasing over #219 and see if this passes CI now?

**Comment by alexcrichton** [comment]
The sizing bits look good (thanks @heiher!) but it looks like there may be new runtime dependencies on Windows? Probably "just" a missing `-l` argument though (unsure which one myself without googling further)

**Comment by heiher** [comment]
> Oh I think that the line you'll need to modify is [around here](https://github.com/alexcrichton/openssl-src-rs/blob/main/src/lib.rs#L690)

Fixed: https://github.com/alexcrichton/openssl-src-rs/pull/221

**Comment by amousset** [comment]
Thanks @heiher, I picked your commit (sorry for the latency, I'm not very available these days).

**Pull request merged**
