### PR TITLE
Add aarch64-apple-darwin to CI

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Comment by shepmaster** [comment]
Hmm. Any suggested way you want me to change it to do a build-but-not-run test?

```
    Finished test [unoptimized + debuginfo] target(s) in 1m 00s
     Running `/Users/runner/work/openssl-src-rs/openssl-src-rs/target/aarch64-apple-darwin/debug/deps/testcrate-771f9a4a8d42eef2`
```

**Comment by alexcrichton** [comment]
Other builders [do this](https://github.com/alexcrichton/openssl-src-rs/blob/8338b33a01b4e4ad777d3f06b21415466b6ebf95/ci/docker/aarch64-unknown-linux-gnu/Dockerfile#L11), so perhaps that could work for this target as well?

**Comment by shepmaster** [comment]
That’s nasty and I love it.

**Comment by shepmaster** [comment]
Test failure looks unrelated / spurious.

**Comment by alexcrichton** [comment]
Looks great to me, thanks!

**Pull request merged**
